service:
  port: ":9888"
  secret_key: "your_secret_key_here"

database:
  host: "127.0.0.1"
  port: 3308
  user: "your_db_user"
  password: "your_db_password"
  name: "your_database_name"
  timezone: "Asia/Jakarta"
  parse_time: true
  multi_statements: true

smtp:
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  smtp_sender_name: "Simple Blog"
  smtp_sender_email: "your_email@gmail.com"
  smtp_password: "your_app_password"
